# -*- coding: utf-8 -*-
"""calculadora mod1.14 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GddX7Pg_4y4pJNYxWrpPtQTJxFuVG0Pa
"""

from genericpath import isfile
print ("Bem vindo à calculadora. \n Digite um numero para começar:" )

x = float(input())
print ("\n O numero digitado foi:", x, ".Digite outro numero para continuar:")

y = float(input())
print ("\n O numero digitado foi:", y)

print ("\n\n Escolha uma operação:")
print ("A - Soma")
print ("B - Subtração")
print ("C - Multiplicação")
print ("D - Divisão")
print ("E - Resto da divisão")

a = x + y
b = x - y
c = x * y
d = x / y
e = x % y

calc = input("\n A operação escolhida foi:")

if calc == "A" or calc == "a":
  print("A soma dos dois numeros é:", a, "\n")

elif calc == "B" or calc == "b":
    print("A subtração dos dois numeros é:", b, "\n")

elif calc == "C" or calc == "c":
    print("A multiplicação dos dois numeros é:", c, "\n")

elif calc == "D" or calc == "d":
    print("A divisão dos dois numeros é:", d, "\n")

elif calc == "E" or calc == "e":
    print("O resto da divisão dos dois numeros é:", e, "\n")

else:
    print("Operação inválida.")

#################################
func = input("Escolha (C) para continuar ou (S) para sair:\n")

if func == "c" or func == "C":
    True

while True:
    print("Bem vindo à calculadora. \n Digite um numero para começar:")
    x = float(input())
    print("\n O numero digitado foi:", x, ".Digite outro numero para continuar:")
    y = float(input())
    print("\n O numero digitado foi:", y)
    print ("\n\n Escolha uma operação:")
    print ("A - Soma")
    print ("B - Subtração")
    print ("C - Multiplicação")
    print ("D - Divisão")
    print ("E - Resto da divisão")

    a = x + y
    b = x - y
    c = x * y
    d = x / y
    e = x % y

    calc = input("\n A operação escolhida foi:")
    if calc == "A" or calc == "a":
      print("A soma dos dois numeros é:", a, "\n")

    elif calc == "B" or calc == "b":
        print("A subtração dos dois numeros é:", b, "\n")

    elif calc == "C" or calc == "c":
        print("A multiplicação dos dois numeros é:", c, "\n")

    elif calc == "D" or calc == "d":
        print("A divisão dos dois numeros é:", d, "\n")

    elif calc == "E" or calc == "e":
        print("O resto da divisão dos dois numeros é:", e, "\n")

    else:
        print("Operação inválida.")

    func = input("Escolha (C) para continuar ou (S) para sair:\n")
    if func == "c" or func == "C":
        True
    else:    break


if func == "S" or func == "s":
    print("Obrigado por usar a calculadora. Até a próxima!")
else:
  print ("Operação inválida.")

